server:
  servlet:
    context-path: /simple-budgeting

############################## DB conf ##############################
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/simple-budgeting-demo
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

jwt:
  secret: Y0W7GgFjc8DXIYudhJ0iP2zFvMJcvrD6jorWBorUnWjorWBorUnWjorWBorUnW
  expiration: 86400000

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs.path: /api-docs